DROP SCHEMA IF EXISTS public CASCADE;

CREATE SCHEMA public;

DROP TABLE IF EXISTS roles CASCADE;

CREATE TABLE roles
(
    id   INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) UNIQUE NOT NULL
);

DROP TABLE IF EXISTS privileges CASCADE;

CREATE TABLE privileges
(
    id   INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) UNIQUE NOT NULL
);

DROP TABLE IF EXISTS role_privileges CASCADE;

CREATE TABLE role_privileges
(
    role_id      INTEGER REFERENCES roles (id),
    privilege_id INTEGER REFERENCES privileges (id),
    PRIMARY KEY (role_id, privilege_id)
);

DROP TABLE IF EXISTS users CASCADE;

CREATE TABLE users
(
    id       INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email    VARCHAR(255) UNIQUE,
    password VARCHAR(255) NOT NULL,
    role_id  INT REFERENCES roles (id)
);

DROP TABLE IF EXISTS contracts CASCADE;

CREATE TABLE contracts
(
    id      INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INT REFERENCES users (id),
    status  VARCHAR(255) DEFAULT 'PENDING'
);

DROP TABLE IF EXISTS events CASCADE;

CREATE TABLE events
(
    id          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     INT REFERENCES users (id),
    name        VARCHAR(255)          UNIQUE NOT NULL,
    description TEXT                  NOT NULL,
    price       INT CHECK (price > 0) NOT NULL
);

DROP TABLE IF EXISTS user_event_participations;

CREATE TABLE user_event_participations
(
    id                    INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id               INT REFERENCES users (id),
    event_id              INT REFERENCES events (id),
    status                VARCHAR(255) DEFAULT 'PENDING',
    fio                   VARCHAR(255) NOT NULL,
    age                   INT          NOT NULL CHECK (age > 0) CHECK (age < 150),
    covid_passport_number INT          NOT NULL,
    UNIQUE (user_id, event_id)
);
